#config.yml

general:
  decks: consecutive                               # must be "consecutive" or "list"
  first deck number: 0                             # non-negative integer less than 10,000
  number of decks to be played: 10                 # positive integer no more than 10,000 minus first deck number
  list:                                            # not implemented
  suit symbol: icon                                # must be "icon" or "alpha"
  rank symbol: number                              # must be "number" or "alpha"
  type of play: playAll                           # must be playAll or playOrig
  verbose: 0                                       # must be non-negative integer
  outputTo: C                                      # not implemented

play original:
   length of initial override strategy: 8           # non-negative integer

play all moves:
  # level of deck by deck reporting
  deck by deck result report: short                # must be "short" or "long"

  # after how many every moves should the interim result be printed, in millions
  move count reporting points (in millions): 5     #

  # should a win loss record be printed at the end
  win loss record: true                            # must be true or false

  find all winning strategies?: false              # must be false or true
  print move detail?: false
  print move detail options:
    type:                                          # must be TW, TS, super short, short, long
    starting deck number: 0
    continue for how many decks: 0
    starting move number: 0
    continue for how many moves: 0
